### ISSUE TITLE
Error when running r31jp <filename?

### ISSUE THREAD

**Issue by vpontis** [nitsky/r31jp#1]
I ran `r31jp <filename>` and got the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/r31jp", line 95, in <module>
    main()
  File "/usr/local/bin/r31jp", line 54, in main
    port = serial.Serial(options.serialport, baudrate=options.baudrate)
  File "/Library/Python/2.7/site-packages/serial/serialutil.py", line 282, in __init__
    self.open()
  File "/Library/Python/2.7/site-packages/serial/serialposix.py", line 289, in open
    self.fd = os.open(self.portstr, os.O_RDWR|os.O_NOCTTY|os.O_NONBLOCK)
OSError: [Errno 2] No such file or directory: '/dev/tty.usbserial'
```

Any ideas on what I should do?

**Comment by vpontis** [comment]
I'm pretty sure that this is because my prolific USB serial driver isn't installing. I have the new MacBook Air and am running the newest version of OS X. Is anyone else having this problem?

**Comment by nitsky** [comment]
Hi Victor, it's definitely because the script can't find the USB serial device. Try this with your usb serial converter plugged in to list all available tty devices:
ls /dev/tty.*

**Comment by vpontis** [comment]
Sweet, that makes a lot of sense. For some reason I thought installing the driver would fix that but now I realize I need the device.

**Comment by nitsky** [comment]
@vpontis were you able to get things working?

**Comment by vpontis** [comment]
Yep, it works great now! Thank you so much. I just got my serial device in the mail yesterday.

Is the best way to exit out of the screen session `C-a -> :quit`?

**Comment by nitsky** [comment]
Yes, that’s right. After long hours in the lab it becomes muscle memory. :)

**Comment by vpontis** [comment]
:+1: sweet, thanks dude!
