### ISSUE TITLE
Tag Creation

### ISSUE THREAD

**Issue by aboolean** [nitsky/r31jp#4]
Homebrew is not installing the latest version of the r31jp repo, since the Formula file downloads the "0.1.tar.gz" archive from a previous commit.

I would really appreciate if you could run:
```
git checkout master
git tag 0.2
git push origin --tags
```

**Comment by nitsky** [comment]
Hi @aboolean, I confirmed that the formula did not install and I believe I have fixed it. I updated the SHA values for homebrew and clarified that you have to install pyserial. Following the instructions in the README, I was able to install the formula and run the script. Please let me know if you need anymore help getting up and running.

**Comment by aboolean** [comment]
Hi @nitsky, thanks for the hash fix. I should provide some context...I'm a 6.115 TA and your r31jp script is used by many students every term. It's extremely helpful, and I've been using it myself for a while now. I tend to install the python script manually, whereas most students use the homebrew method. I wanted to make sure the homebrew installation produced a consistent script to this repo.

Homebrew installs an archived version of the repo named "0.1" (from the tag, not the branch). This version is 7 commits behind master. To bring this up to date, it would be helpful if you would create the 0.2 tag for the current master branch, as above.

Then, the homebrew Formula could be made to reference "[.....]/archive/0.2.tar.gz" to install the most current version.

**Comment by nitsky** [comment]
I'm glad to hear this script is being used! I created a version 0.2 tag and updated the homebrew formula :)

**Comment by aboolean** [comment]
Excellent, it works! Thanks for putting the effort in to maintain this project; it's very much appreciated!
